# Generated by Django 4.2.5 on 2023-09-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")], max_length=100),
                ),
                ("accounts", models.ManyToManyField(blank=True, to="sales.contacts")),
            ],
        ),
        migrations.CreateModel(
            name="Deals",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deal", models.CharField(max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[("Discovery", "Discovery"), ("Proposal", "Proposal"), ("Negotiation", "Negotiation")],
                        max_length=100,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.accounts")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.contacts")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
